import { Rule } from "./types";

export const seedRules: Rule[] = [
  {
    id: "R-001",
    name: "기본 근무 기준",
    desc: "일반 근무 시간 계산 기준",
    useYn: "사용",
    tags: ["basic"],
    timeUnit: "1분",
    rounding: "버림",
    dayRange: { start: { hh: "00", mm: "00" }, end: { hh: "23", mm: "59" } },

    excludeEnabled: true,
    excludeOutside: true,
    excludeBreak: true,

    earlyEnabled: false,
    earlyMode: "기본근무 시작 시간 이전",
    earlyStart: { hh: "00", mm: "00" },
    earlyEnd: { hh: "00", mm: "00" },
    earlyMin: "1분",
    earlyMax: "60분",
    earlyExcludeFromBasic: false,

    overtimeEnabled: false,
    overtimeMode: "기본근무 초과",
    overtimeMin: "1분",
    overtimeMax: "120분",
    overlapPolicy: "근무 유형별 분리 인정",
    overlapEarly: false,
    overlapNight: true,
    overlapHoliday: true,

    nightEnabled: false,
    nightStart: { hh: "22", mm: "00" },
    nightEnd: { hh: "06", mm: "00" },
    nightCrossDay: true,
    nightMin: "1분",
    nightMax: "120분",
    nightExcludeFromBasic: false,

    holidayEnabled: false,
    holidayBasis: "공휴일 캘린더",
    holidayAbsenceIgnore: true,
    holidayMin: "1분",
    holidayMax: "120분",
    holidayExcludeFromBasic: false,
  },
  {
    id: "R-002",
    name: "야간 근무 기준",
    desc: "야간 근무시간 계산 기준",
    useYn: "사용",
    tags: ["basic","night"],
    timeUnit: "1분",
    rounding: "버림",
    dayRange: { start: { hh: "00", mm: "00" }, end: { hh: "23", mm: "59" } },

    excludeEnabled: true,
    excludeOutside: true,
    excludeBreak: true,

    earlyEnabled: false,
    earlyMode: "기본근무 시작 시간 이전",
    earlyStart: { hh: "00", mm: "00" },
    earlyEnd: { hh: "00", mm: "00" },
    earlyMin: "1분",
    earlyMax: "60분",
    earlyExcludeFromBasic: false,

    overtimeEnabled: false,
    overtimeMode: "기본근무 초과",
    overtimeMin: "1분",
    overtimeMax: "120분",
    overlapPolicy: "근무 유형별 분리 인정",
    overlapEarly: false,
    overlapNight: true,
    overlapHoliday: true,

    nightEnabled: true,
    nightStart: { hh: "22", mm: "00" },
    nightEnd: { hh: "06", mm: "00" },
    nightCrossDay: true,
    nightMin: "1분",
    nightMax: "120분",
    nightExcludeFromBasic: false,

    holidayEnabled: false,
    holidayBasis: "공휴일 캘린더",
    holidayAbsenceIgnore: true,
    holidayMin: "1분",
    holidayMax: "120분",
    holidayExcludeFromBasic: false,
  },
  {
    id: "R-003",
    name: "휴일 근무 기준",
    desc: "공휴일 근무시간 계산 기준",
    useYn: "사용",
    tags: ["basic","holiday"],
    timeUnit: "1분",
    rounding: "버림",
    dayRange: { start: { hh: "00", mm: "00" }, end: { hh: "23", mm: "59" } },

    excludeEnabled: true,
    excludeOutside: true,
    excludeBreak: true,

    earlyEnabled: false,
    earlyMode: "기본근무 시작 시간 이전",
    earlyStart: { hh: "00", mm: "00" },
    earlyEnd: { hh: "00", mm: "00" },
    earlyMin: "1분",
    earlyMax: "60분",
    earlyExcludeFromBasic: false,

    overtimeEnabled: false,
    overtimeMode: "기본근무 초과",
    overtimeMin: "1분",
    overtimeMax: "120분",
    overlapPolicy: "근무 유형별 분리 인정",
    overlapEarly: false,
    overlapNight: true,
    overlapHoliday: true,

    nightEnabled: false,
    nightStart: { hh: "22", mm: "00" },
    nightEnd: { hh: "06", mm: "00" },
    nightCrossDay: true,
    nightMin: "1분",
    nightMax: "120분",
    nightExcludeFromBasic: false,

    holidayEnabled: true,
    holidayBasis: "공휴일 캘린더",
    holidayAbsenceIgnore: true,
    holidayMin: "1분",
    holidayMax: "120분",
    holidayExcludeFromBasic: false,
  },
  {
    id: "R-004",
    name: "휴일연장 근무 기준",
    desc: "휴일 + 연장 근무시간 계산 기준",
    useYn: "미사용",
    tags: ["basic","holiday","overtime"],
    timeUnit: "10분",
    rounding: "반올림",
    dayRange: { start: { hh: "00", mm: "00" }, end: { hh: "23", mm: "59" } },

    excludeEnabled: true,
    excludeOutside: true,
    excludeBreak: true,

    earlyEnabled: false,
    earlyMode: "기본근무 시작 시간 이전",
    earlyStart: { hh: "00", mm: "00" },
    earlyEnd: { hh: "00", mm: "00" },
    earlyMin: "10분",
    earlyMax: "60분",
    earlyExcludeFromBasic: false,

    overtimeEnabled: true,
    overtimeMode: "기본근무 초과",
    overtimeMin: "10분",
    overtimeMax: "120분",
    overlapPolicy: "최대 1개만 인정",
    overlapEarly: false,
    overlapNight: true,
    overlapHoliday: true,

    nightEnabled: false,
    nightStart: { hh: "22", mm: "00" },
    nightEnd: { hh: "06", mm: "00" },
    nightCrossDay: true,
    nightMin: "10분",
    nightMax: "120분",
    nightExcludeFromBasic: false,

    holidayEnabled: true,
    holidayBasis: "공휴일 캘린더",
    holidayAbsenceIgnore: true,
    holidayMin: "10분",
    holidayMax: "120분",
    holidayExcludeFromBasic: false,
  },
  {
    id: "R-005",
    name: "야간·휴일 근무 기준",
    desc: "야간 및 휴일 근무 시간 계산 기준",
    useYn: "미사용",
    tags: ["basic","night","holiday"],
    timeUnit: "15분",
    rounding: "버림",
    dayRange: { start: { hh: "00", mm: "00" }, end: { hh: "23", mm: "59" } },

    excludeEnabled: true,
    excludeOutside: true,
    excludeBreak: true,

    earlyEnabled: false,
    earlyMode: "기본근무 시작 시간 이전",
    earlyStart: { hh: "00", mm: "00" },
    earlyEnd: { hh: "00", mm: "00" },
    earlyMin: "15분",
    earlyMax: "60분",
    earlyExcludeFromBasic: false,

    overtimeEnabled: false,
    overtimeMode: "기본근무 초과",
    overtimeMin: "15분",
    overtimeMax: "120분",
    overlapPolicy: "근무 유형별 분리 인정",
    overlapEarly: false,
    overlapNight: true,
    overlapHoliday: true,

    nightEnabled: true,
    nightStart: { hh: "22", mm: "00" },
    nightEnd: { hh: "06", mm: "00" },
    nightCrossDay: true,
    nightMin: "15분",
    nightMax: "120분",
    nightExcludeFromBasic: false,

    holidayEnabled: true,
    holidayBasis: "공휴일 캘린더",
    holidayAbsenceIgnore: true,
    holidayMin: "15분",
    holidayMax: "120분",
    holidayExcludeFromBasic: false,
  },
];
